module.exports = {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './vendor/lunarphp/stripe-payments/resources/views/**/*.blade.php',
    ],
    safelist: [
        'bg-slate-600',
        'border-slate-600',
        'hover:bg-slate-700',
        'bg-slate-700',
        'hover:bg-slate-600',
        'bg-slate-800',
        'hover:bg-slate-800',
        'bg-slate-500',
        'hover:bg-slate-500',
        'text-slate-600',
        'text-slate-700',
        'border-slate-700',
        'focus:ring-slate-600',
        'focus:ring-slate-700',
        'focus:border-slate-600',
        'focus:border-slate-700',
        'active:bg-slate-900',
        'focus:ring-slate-200',
        'focus:border-slate-300',
        'text-slate-400',
        'text-slate-500',
        'bg-slate-50',
        'border-slate-300',
    ],
    theme: {
        extend: {},
    },
    plugins: [require('@tailwindcss/forms')],
};
